config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :photos
  resources :pets
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  root 'welcome#index', as: 'welcome_index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  belongs_to :parent, class_name: "Pet", optional: true
  has_many :children, class_name: "Pet", foreign_key: "parent_id"
  has_many :photos, dependent: :destroy
  
  validates :name, presence: true
  validates :description, presence: true
  validates :animal_type, presence: true
  validates :breed, presence: true
  

  def owned_by(current_user) 
  	return user.id == current_user.id
  end

  def parent_name
    parent.try(:name)
  end

  def has_parent?
    parent.present?
  end

  def has_children?
    childern.exists?
  end

  def same_type(type)
    animal_type == type
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  include CurrentUser
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:new, :show, :edit, :create, :update, :destroy]
  before_action :check_if_owner, only: [:edit, :update, :destroy]
  before_action :set_all_pets, only: [:index, :new, :edit, :create, :update]
  after_action :check_animal_type, only: [:create, :update]
  # GET /pets
  # GET /pets.json
  def index
    
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
    session[:pet_id] = @pet.id
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
    
  end

  # POST /pets
  # POST /pets.json
  def create 
    @pet = Pet.new(pet_params)
    @pet.user = @user
    
    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    session[:pet_id] = nil
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to @user, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :description, :animal_type, :breed, :user_id, :parent_id)
    end

    def set_all_pets
      @pets = Pet.all
    end

    def check_animal_type
      if @pet.has_parent?
        unless @pet.same_type(@pet.parent.animal_type)
          @pet.parent_id = nil
          @pet.save
          puts "********"
          puts "not same type"
          puts "********"
        end
      end
      
    end

end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<%= form_with(model: pet, local: true) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :animal_type %>
    <%= form.text_field :animal_type %>
  </div>

  <div class="field">
    <%= form.label :breed %>
    <%= form.text_field :breed %>
  </div>

  <div class="field">
    <%= form.label :chose_parent %>
    <%= form.select :parent_type, @pets.map{ |pet| [pet.animal_type]} %>
    <%= form.select :parent_id, @pets.map{ |pet| [pet.name, pet.id]}, include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Type</th>
      <th>Breed</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.description %></td>
        <td><%= pet.animal_type %></td>
        <td><%= pet.breed %></td>
        <td><%= pet.user.name %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<section>
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
      <p id="notice"><%= notice %></p>
      <table>
        <thead>
          <tr>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th><strong>Name:</strong></th>
            <td><%= @pet.name.capitalize %></td>
          </tr>
          
          <tr>
            <th><strong>Type:</strong></th>
            <td><%= @pet.animal_type %></td>
          </tr>

          <tr>
            <th><strong>Breed:</strong></th>
            <td><%= @pet.breed %></td>
          </tr>

          <tr>
            <th><strong>Owner:</strong></th>
            <td><%= link_to @pet.user.name, @pet.user %></td>
          </tr>

          <% if @pet.has_parent? %>
            <tr>
              <th><strong>Parent: </strong></th> 
                <td><%= link_to @pet.parent.name, @pet.parent %></td>
            </tr>
          <% end %>

          <tr>
            <th><strong>Description:</strong></th>
            <td><%= @pet.description %></td>
          </tr>
        </tbody>
      </table>


      <p>
        
      </p>
    </div>
    <div class="col-sm-1"></div>
  </div>
  
</section>


<section>
  <div class=row>
    <div class="col-sm-1"></div>
    <div class="pet_photos col-sm-11">
      <div class="card-columns">
        <% @pet.photos.each do |photo| %>
          <div class="card">
            <%= image_tag(photo.pet_image, style:"width:100%",class: "img-fluid card-img-top") %>
            <div class="card-body">
              <h5 class="card-title"><%= photo.title %></h5>
              <p class="card-text"><%= photo.description %></p>
              <% if @pet.owned_by(@user) %>
                <p class="card-text">
                  <%= link_to 'Edit photo', edit_photo_path(photo) %>
                  <%= link_to 'Delete photo', photo, method: :delete, data: { confirm: 'Are you sure?' } %> 
                  </p>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section> 



<% if @pet.owned_by(@user) %>
  <%= link_to 'Edit', edit_pet_path(@pet) %> |
  <%= link_to 'Add photo', new_photo_path %> |
<% end%>

<%= link_to 'Back', @user %>