config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :photos
  resources :pets
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  root 'welcome#index', as: 'welcome_index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pets, dependent: :destroy
  has_many :posts, dependent: :destroy
  
  has_one_attached :profile_image
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true

  def is_current_user(session_user_id)
  	if self.id == session_user_id
  		puts "****"
  		puts "CURRENT USER"
  		puts "****"

  		return true
  	else
  		puts "****"
  		puts "NOT CURRENT USER"
  		puts "****"

  		return false
  	end
  end

  def has_no_pets
    pets.count < 1
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include CurrentUser
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:new, :create]
  before_action :check_if_current_user, only: [:edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @pets = @user.pets
    @current_user = User.find(session[:user_id])

    @is_current_user = @user == @current_user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.is_current_user(session[:user_id])
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      puts "CANNOT UPDATE ANOTHER USER"
      redirect_to welcome_index_url, notice: 'Cannot update another users data.'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user.is_current_user(session[:user_id])
      @user.destroy
      session[:user_id] = nil
      redirect_to welcome_index_url
    else
      puts "CANNOT DELETE ANOTHER USER"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name, :profile_image)
    end

   
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="filed">
    <%= form.label :profile_image %>
    <%= form.file_field :profile_image %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit "Submit"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8 text-left">
      <h1>Users</h1>

      <table>
        <thead>
          <tr align="left">
            <th> Photo </th>
            <th> Name </th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag(user.profile_image, size: "200x100", class: "img-fluid") if user.profile_image.attached? %></td>
              <td><%= user.name %></td>
              <td><%= link_to 'Show profile', user %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

    </div>  
    <div class="col-sm-2"></div>

app/views/users/new.html.erb
<h1>Add New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<div class="user_profile">
	<div class="row">
		<div class="col-sm-3"></div>
		<div class="col-sm-8 text-left">
			<p id="notice"><%= notice %></p>
			<% if @is_current_user %>
				<h1>My Profile</h1>
				<% else %>
				<h1><%= @user.name %>'s profile</h1>
			<% end %>
			<div class="row">
				<div class="col-sm-4">
					<%= image_tag(@user.profile_image, style:"width:100%",class: "img-fluid") if @user.profile_image.attached? %>
				</div>
				<div class="col-sm-4">
					<p><strong>Name: </strong><%= @user.name %></p>
					<% if @is_current_user%>
						<p><strong>Email: </strong><%= @user.email %></p>
					<% end %>
				</div>
			</div>
			
		</div>
		<div class="col-sm-1"></div>
	</div>

	<div class="row">
		<div class="col-sm-3">
			<% unless @user.has_no_pets %>
				<div class="pets_list">
					<table>
					  <thead>
					  	<tr><h5>Pets</h5></tr>
					    <tr>
					      <th>Name</th>
					      <th>Type</th>
					      <th>Breed</th>
					      <th colspan="3"></th>
					    </tr>
					  </thead>

					  <tbody>
					    <% @pets.each do |pet| %>
					      <tr>
					        <td><%= pet.name %></td>
					        <td><%= pet.animal_type %></td>
					        <td><%= pet.breed %></td>
					        <td><%= link_to 'Show', pet %></td>

					        <% if pet.owned_by(@current_user) %>
						        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
						        <td><%= link_to 'Delete', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
					        <% end %>
					      </tr>
					    <% end %>
					  </tbody>
					</table>
				</div>
			<% end %>
			<% if @is_current_user %>
				<%= link_to 'Add pet', new_pet_path %>
			<% end %>
		</div>
		<div class="col-sm-6 text-left">
			<% if @is_current_user %>
				<div>
					<strong><%= link_to	'Add new post', new_post_path %></strong>
				</div>
			<% end %>
			<div>
				<% unless @user.posts.empty? %>
				<br>
					<h4> Posts </h4>
					<% @user.posts.each do |post| %>
						<div class="card">
							<div class="card-body">
								<strong><%= post.user.name %> posted 
							</div>	
							<div class="card-title"></strong> <%= post.body %></div>
							<div >
								<%= image_tag(post.users_photo, style:"width:100%", class: "img-fluid card-img-top") if post.users_photo.attached? %>
							</div>
							<div class="card-text">
								<% if @is_current_user %>
									<%= link_to	'Edit post', edit_post_path(post) %>
									<%= link_to 'Delete post', post, method: :delete %>
									<% end %>
							</div>
							
						</div>	
						<br>
					<% end %>
				<% end %>
			</div>

		</div>
		<div class="col-sm-2">
			<% if @is_current_user %>
				<%= link_to 'Edit', edit_user_path(@user) %> |
				<%= link_to 'Delete profile', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
			<% end %>
		</div>
	</div>
</div>
	